### ISSUE TITLE
No Pokemon for imported decks

### ISSUE THREAD

**Issue by hackelle** [shigeyukey/Pokemanki-Gold#1] opened 2024-01-09 23:00 UTC
Whenever I start a new deck which I imported, I don't get the new Pokemon. For my own decks it works, for imported ones it does not. The same issue I have in [Pokemanki](https://ankiweb.net/shared/info/1041307953) and I also [reported](https://github.com/zjosua/Pokemanki/issues/45) it already before. 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-10-17T23:29, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
Pokemanki Gold ['1677779223', 2024-01-05T10:53, 'None', '']
Progress Bar original ['1685464019', 2022-07-28T07:24, 'None', '']
Remove Duplicate Cards ['95590040', 2021-05-05T20:12, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1374772155 1677779223 1685464019 1771074083 95590040

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

I am now using MacOS 14.2.1 (compared to windows in the other report) and it is the same issue.

**Comment by shigeyukey** [comment] 2024-01-09 23:26
Hi, thank you for the error report.
I have read your earlier report, but cannot seem to reproduce the problem.(Pokemon are displayed when using an imported shared deck).
What kind of deck are you importing?

**Comment by lhackel-tub** [comment] 2024-01-09 23:38
Hello,
Thank you for the fast reply. It is with .apkg decks (happens on multiple decks) and also the ankiphil deck from amboss

**Comment by shigeyukey** [comment] 2024-01-10 12:02
Hmm, there seems to be no problem with the ankiphil deck and add-ons.

1. when there are many cards, like medical decks, it takes a bit of time for the first pokemon to appear.
( Own deck has fewer cards, so Pokemon appears quickly.)
Wouldn't pokemon appear when the imported deck is reviewed more?
For example, import the same deck to another profile and flip through many cards.
(You can check this by pressing "Stats" while learning) 

2. Pokemon will appear in the bottom sub-deck.
\+ Parent deck
  ___-  Subdeck
  ______- Subdeck ←[ here ]
So you may not be able to see Pokémon from the parent deck.
(Or, if you delete the sub decks, the number of cards in the parent deck will increase so that the first Pokémon will take more time to appear.)

3. Otherwise, there may be something wrong with the decks. Can you share the problem decks with me so I can try to reproduce the issue? ( media is not required )

**Comment by hackelle** [comment] 2024-01-10 20:40
Is the level of the pokemon / when they are appearing first depending on the percentage of cards learned or how is the level defined?

**Comment by shigeyukey** [comment] 2024-01-10 22:09
The Pokemon level and first appearance depend on the percentage of learned cards.
Deck to be calculated is a sub-deck with no parent.
The first Pokemon appears when about 5% of the cards are learned.
So if there are about 500 cards in the sub-deck, the first Pokemon will appear in about 20 cards.
If there are about 2,000 cards in the sub-deck, the first Pokemon will appear in about 100 cards.

**Comment by hackelle** [comment] 2024-01-10 22:23
Ah thank you. That also explains how Pokemon can "unlevel" (as in loose levels). If cards are added, the percentage goes down and therefore the level goes down, right?

**Comment by shigeyukey** [comment] 2024-01-10 23:04
The original Pokemanki reported that when new cards are added the level goes down, so probably yes.
But more cards will appear higher grade Pokemon, so it is better to add more cards.
(i.e. it will be easier to find rare Pokemon in trades).

**Comment by shigeyukey** [comment] 2024-01-13 16:17
Perhaps the problem seems to be the number of cards, so close this issue as complete.
If the cause is not so, please reopen.

**Closed as completed by shigeyukey** 2024-01-13 16:17 UTC
Labels: bug

**Comment by lhackel-tub** [comment] 2024-03-05 15:39
To complete this, the issue was the number of cards — after using the deck more, the Pokemon appeared, and the same with "unleveling." The Pokemon only lost level when new cards were added.

This is not a bug.
